FROM mongo:latest

RUN apt-get update && apt-get install -y --no-install-recommends \
    net-tools \
    iputils-ping \
    wget && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


# Set the bind IP for MongoDB
#ENV MONGO_BIND_IP=172.18.0.2

# Expose the MongoDB port
EXPOSE 27017

# Create a directory for MongoDB data
RUN mkdir -p /data/db

# Set the working directory
WORKDIR /data/db

# Copy any MongoDB initialization scripts if needed
#COPY init-mongo.js /docker-entrypoint-initdb.d/

# Start MongoDB
CMD ["mongod", "--bind_ip", "172.18.0.2"]
