FROM mongo:latest

# Expose the MongoDB port
EXPOSE 27017

# Create a directory for MongoDB data
RUN mkdir -p /data/db

# Set the working directory
WORKDIR /data/db

# Copy any MongoDB initialization scripts if needed
#COPY init-mongo.js /docker-entrypoint-initdb.d/

# Start MongoDB
CMD ["mongod"]
